#
# FutHelpers.cmake — CMake utilities bundled with the FUT library.
#
# Included automatically when the package is found via find_package or CPM.
#
# ─────────────────────────────────────────────────────────────────────────────
#
# fut_catch2_discover(<target> <fortran_reg_fn>)
#
#   Attaches a Catch2 auto-discovery driver to an existing CMake target so
#   that every Fortran test suite registered with fut_register_test() becomes
#   an independent Catch2 test case — without the user writing any C++ code.
#
#   The function generates a tiny C++ translation unit in the build directory:
#
#     #include "fut_catch2.hpp"
#     extern "C" { void <fortran_reg_fn>(void); }
#     FUT_AUTO_DISCOVER_TESTS(<fortran_reg_fn>)
#
#   and appends it to <target>'s SOURCES.
#
#   Parameters:
#     target           CMake target for the test executable.
#     fortran_reg_fn   Name of the bind(C) Fortran subroutine that calls
#                      fut_register_test() for each test suite.
#
#   Requirements:
#     • <target> must link against fortran_unit_test and Catch2::Catch2WithMain.
#     • <fortran_reg_fn> must be a bind(C) subroutine with no arguments.
#
#   Typical usage:
#
#     add_executable(physics_tests tests/physics_tests.F90)
#     target_link_libraries(physics_tests PRIVATE
#       physics fortran_unit_test Catch2::Catch2WithMain)
#     fut_catch2_discover(physics_tests register_physics_tests)
#
function(fut_catch2_discover target fortran_reg_fn)
    set(_gen "${CMAKE_CURRENT_BINARY_DIR}/_fut_${target}_catch2_main.cpp")
    file(WRITE "${_gen}"
"// Auto-generated by fut_catch2_discover() — do not edit.\n"
"// Re-run CMake to regenerate after changing the registration function name.\n"
"#include \"fut_catch2.hpp\"\n"
"extern \"C\" { void ${fortran_reg_fn}(void); }\n"
"FUT_AUTO_DISCOVER_TESTS(${fortran_reg_fn})\n"
    )
    target_sources(${target} PRIVATE "${_gen}")
endfunction()
